# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
# (C) 2019 Smile (<http://www.smile.eu>)
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

##########################################################################
# This module is generated by Odoo Studio and converted By Smile Studio2Py
##### You have to add a name, summary and description to this module #####
##########################################################################
{'auto_install': False,
    'installable': True,
    'version': '1.0',
    'summary': '',
    'website': 'https://www.smile.eu',
    'name': 'Generated by studio2py ',
    'post_load': None,
    'description': '',
    'web': False,
    'category': 'Uncategorized',
    'author': 'Smile S.A',
    'application': False,
    'data': ['views/x_departments_views.xml',
             'views/studio_converter_view.xml',
             'views/x_proffessors_views.xml',
             'views/x_subjects_views.xml',
             'views/x_students_views.xml',
             'security/ir.model.access.csv',
             'views/actions.xml',
             'views/menus.xml'],
    'sequence': 100,
    'license': 'AGPL-3.0',
    'depends': ['base',
                'web_studio']}
